# Generated by Django 5.2.3 on 2026-07-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberservicepreset',
            name='plan',
            field=models.JSONField(default=dict),
        ),
    ]
