# Generated by Django 5.2.3 on 2026-07-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_memberservicepreset_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberservicepreset',
            name='plan',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='plan',
            field=models.JSONField(default=dict),
        ),
    ]
