# Generated by Django 5.2.3 on 2026-07-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0003_remove_memberservicepreset_plan_purchaserequest_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpurchase',
            name='plan',
            field=models.JSONField(default=dict),
        ),
    ]
