# Generated by Django 5.2.3 on 2026-07-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceplan',
            name='data_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='data_weight',
            field=models.CharField(blank=True, choices=[('mb', 'MegaByte'), ('gb', 'GigaByte')], default='', max_length=2),
        ),
    ]
