# Generated by Django 5.2.3 on 2026-07-19 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_serviceplan_data_value_serviceplan_data_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiProviderResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_response', to='services.serviceprovider')),
            ],
        ),
    ]
