# Generated by Django 5.2.3 on 2026-07-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_apiproviderresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiproviderresponse',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
