# Generated by Django 5.2.3 on 2026-07-15 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('transaction_type', models.CharField(choices=[('airtime', 'Airtime'), ('data', 'Data'), ('electricity', 'Electricity'), ('cable', 'Cable TV'), ('internet', 'Internet'), ('exam_pin', 'Exam Pin'), ('education', 'Education'), ('wallet_funding', 'Wallet Funding'), ('refund', 'Refund')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wallet_balance_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('wallet_balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('service_provider', models.CharField(blank=True, max_length=100)),
                ('plan_name', models.CharField(blank=True, max_length=200)),
                ('recipient', models.CharField(blank=True, max_length=100)),
                ('reference_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('api_response', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='transaction_user_id_386a11_idx'), models.Index(fields=['status'], name='transaction_status_71abbb_idx'), models.Index(fields=['transaction_type'], name='transaction_transac_09d7ec_idx')],
            },
        ),
    ]
