# Generated by Django 5.2.3 on 2026-07-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
