# Generated by Django 5.2.3 on 2026-07-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='transaction_pin_hash',
            field=models.CharField(blank=True, help_text='Hashed transaction PIN', max_length=128, null=True),
        ),
    ]
