# Generated by Django 5.2.3 on 2026-07-15 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('service_type', models.CharField(choices=[('airtime', 'Airtime'), ('data', 'Data')], max_length=20)),
                ('provider', models.CharField(max_length=100)),
                ('plan_name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_slots', models.PositiveIntegerField(default=1)),
                ('used_slots', models.PositiveIntegerField(default=0)),
                ('expiry_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('expired', 'Expired'), ('completed', 'Completed')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Personal notes about this link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_by', models.CharField(blank=True, help_text='Phone number of claimant', max_length=100)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('is_claimed', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='links.claimlink')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
