# Generated by Django 5.2.3 on 2026-07-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimlink',
            name='plan_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
