# Generated by Django 5.2.3 on 2026-07-18 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_claimlink_plan_id'),
        ('services', '0002_serviceplan_data_value_serviceplan_data_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='claimlink',
            old_name='amount',
            new_name='amount_per_slot',
        ),
        migrations.RemoveField(
            model_name='claimlink',
            name='plan_id',
        ),
        migrations.AddField(
            model_name='claimlink',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_links', to='services.serviceprovider'),
        ),
        migrations.AddField(
            model_name='claimlink',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_links', to='services.serviceplan'),
        ),
        migrations.AlterField(
            model_name='claimlink',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='claimlink',
            name='link_id',
            field=models.CharField(db_index=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='claimlink',
            name='plan_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='claimslot',
            name='is_claimed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='claimlink',
            index=models.Index(fields=['user', 'status'], name='links_claim_user_id_fa7ee6_idx'),
        ),
        migrations.AddIndex(
            model_name='claimlink',
            index=models.Index(fields=['status', 'expiry_date'], name='links_claim_status_c628db_idx'),
        ),
    ]
