# Generated by Django 5.2.3 on 2026-07-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_rename_amount_claimlink_amount_per_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimlink',
            name='plan',
            field=models.JSONField(default={}),
        ),
    ]
