# Generated by Django 5.2.3 on 2026-07-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_alter_claimlink_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimlink',
            name='plan',
            field=models.JSONField(default=dict),
        ),
    ]
